Hacking on m1 support with Chris, Harry, Harshad, Patrick
INCATools/oakx-grape pull request #13
Opened 2022-10-20 19:59 UTC by justaddcoffee

2022-10-28 16:16 UTC, justaddcoffee commented
This PR, in combination with [these other steps that @caufieldjh @hrshdhgd @cmungall put together](https://docs.google.com/document/d/1SAylKLCTnqf0TTPFWJNT_NAWwSXlwETG6WWp9Mdptn0/edit):

- go get an arm-compliant version of python using conda
- `conda create --name oakx-grape-env python=3.9`
- `conda activate oakx-grape-env`
- `pip install poetry`
- `poetry install`
- [Install nvm + npm](https://dev.to/ms314006/how-to-install-npm-through-nvm-node-version-manager-5gif) : Make sure the latest version is installed. 
- Install Graphvis: https://graphviz.org/download/
    -`brew install graphviz`
- `npm install -g obographviz`

Seems to allow oakx-grape to work on M1 macs...

2022-10-31 18:06 UTC, cmungall commented on pyproject.toml
> +bioregistry = "0.5.134"
hmm, this sort of thing shouldn't be necessary but we can revisit

2022-10-31 18:08 UTC, cmungall requested changes
after tests pass, can merge

2022-10-31 18:09 UTC, cmungall commented
can we get the install steps in a readme?

The graphviz stuff isn't necessary though

2022-11-01 16:49 UTC, merged